# Generated by Django 4.2 on 2023-04-16 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complainte',
            options={'ordering': ['downTime']},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['shipingDate']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['dateService']},
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 4, 16), verbose_name='Shiping Date'),
        ),
    ]
