# Generated by Django 4.2 on 2023-04-16 05:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_complainte_downtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.clientcompany', verbose_name='Компания-клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='deliveryAddress',
            field=models.CharField(max_length=256, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='driveAxel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.driveaxel', verbose_name='Ведущая ось'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.engine', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='equipment',
            field=models.CharField(default='стандартная комплектация', max_length=256, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberDriveAxel',
            field=models.CharField(max_length=64, unique=True, verbose_name='Заводской номер ВО'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberEngine',
            field=models.CharField(max_length=64, unique=True, verbose_name='Заводской номер двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberMachine',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True, verbose_name='Заводской номер'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberSteringAxel',
            field=models.CharField(max_length=64, unique=True, verbose_name='Заводской номер УО'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='factoryNumberTransmission',
            field=models.CharField(max_length=64, unique=True, verbose_name='Заводской номер трансмиссии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='modelMachine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.modelmachine', verbose_name='Модель техники'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='receiver',
            field=models.CharField(max_length=64, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 4, 16), verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steringAxel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.steringaxel', verbose_name='Управляемая ось'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='supplyContract',
            field=models.CharField(max_length=64, verbose_name='Договор поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.transmission', verbose_name='Модель трансмиссии'),
        ),
    ]
