# Generated by Django 4.2 on 2023-04-18 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_machine_client_alter_machine_deliveryaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 4, 18), verbose_name='Дата отгрузки'),
        ),
    ]
