# Generated by Django 4.2 on 2023-04-20 13:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_machine_shipingdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainte',
            name='downTime',
            field=models.IntegerField(default=0, verbose_name='Время простоя'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='failureDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='failureDescription',
            field=models.CharField(default='описание', max_length=256, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='failurePart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.parts', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='maintenanceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.maintenancecompany', verbose_name='Компания, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='operatingTime',
            field=models.IntegerField(default=0, verbose_name='Наработка'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='recoveryDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='recoveryMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='complainte',
            name='spareParts',
            field=models.CharField(default='зап.части', max_length=256, verbose_name='Запасные части'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipingDate',
            field=models.DateField(default=datetime.date(2023, 4, 20), verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dateService',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='service',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='service',
            name='operatingTime',
            field=models.IntegerField(default=0, verbose_name='Наработка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='orderDate',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='service',
            name='orderNumber',
            field=models.CharField(max_length=64, verbose_name='№ Заказ-наряд'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='service',
            name='typeOfService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.typeofservice', verbose_name='Тип сервиса'),
        ),
    ]
